// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: invoice.sql

package dbmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO "invoice" (
    transaction_id, price, invoice_image_url, created_at, updated_at
) VALUES (
    $1, $2, $3, NOW(), NOW()
)
RETURNING id, transaction_id, price, invoice_image_url
`

type CreateInvoiceParams struct {
	TransactionID   pgtype.UUID `json:"transactionId"`
	Price           float64     `json:"price"`
	InvoiceImageUrl string      `json:"invoiceImageUrl"`
}

type CreateInvoiceRow struct {
	ID              pgtype.UUID `json:"id"`
	TransactionID   pgtype.UUID `json:"transactionId"`
	Price           float64     `json:"price"`
	InvoiceImageUrl string      `json:"invoiceImageUrl"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (CreateInvoiceRow, error) {
	row := q.db.QueryRow(ctx, createInvoice, arg.TransactionID, arg.Price, arg.InvoiceImageUrl)
	var i CreateInvoiceRow
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.Price,
		&i.InvoiceImageUrl,
	)
	return i, err
}

const getAllInvoices = `-- name: GetAllInvoices :many
SELECT
    id,
    transaction_id,
    price,
    invoice_image_url
from "invoice"
`

type GetAllInvoicesRow struct {
	ID              pgtype.UUID `json:"id"`
	TransactionID   pgtype.UUID `json:"transactionId"`
	Price           float64     `json:"price"`
	InvoiceImageUrl string      `json:"invoiceImageUrl"`
}

func (q *Queries) GetAllInvoices(ctx context.Context) ([]GetAllInvoicesRow, error) {
	rows, err := q.db.Query(ctx, getAllInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllInvoicesRow
	for rows.Next() {
		var i GetAllInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.Price,
			&i.InvoiceImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT
    id,
    transaction_id,
    price,
    invoice_image_url
from "invoice"
WHERE id = $1
`

type GetInvoiceByIDRow struct {
	ID              pgtype.UUID `json:"id"`
	TransactionID   pgtype.UUID `json:"transactionId"`
	Price           float64     `json:"price"`
	InvoiceImageUrl string      `json:"invoiceImageUrl"`
}

func (q *Queries) GetInvoiceByID(ctx context.Context, id pgtype.UUID) (GetInvoiceByIDRow, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, id)
	var i GetInvoiceByIDRow
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.Price,
		&i.InvoiceImageUrl,
	)
	return i, err
}
