// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: mile.sql

package dbmodel

import (
	"context"
)

const createMile = `-- name: CreateMile :one
INSERT INTO "mile" (
    id, rate
) VALUES (
    $1, $2
)
RETURNING id, rate
`

type CreateMileParams struct {
	ID   string  `json:"id"`
	Rate float64 `json:"rate"`
}

func (q *Queries) CreateMile(ctx context.Context, arg CreateMileParams) (Mile, error) {
	row := q.db.QueryRow(ctx, createMile, arg.ID, arg.Rate)
	var i Mile
	err := row.Scan(&i.ID, &i.Rate)
	return i, err
}

const deleteMile = `-- name: DeleteMile :exec
DELETE FROM "mile"
WHERE id=$1
`

func (q *Queries) DeleteMile(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMile, id)
	return err
}

const getMile = `-- name: GetMile :one
SELECT
    rate
FROM "mile"
WHERE id=$1
`

func (q *Queries) GetMile(ctx context.Context, id string) (float64, error) {
	row := q.db.QueryRow(ctx, getMile, id)
	var rate float64
	err := row.Scan(&rate)
	return rate, err
}

const getMiles = `-- name: GetMiles :many
SELECT
    id, 
    rate
FROM "mile"
`

func (q *Queries) GetMiles(ctx context.Context) ([]Mile, error) {
	rows, err := q.db.Query(ctx, getMiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mile
	for rows.Next() {
		var i Mile
		if err := rows.Scan(&i.ID, &i.Rate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
