// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbmodel

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Employee struct {
	ID        pgtype.UUID        `json:"id"`
	Salary    float64            `json:"salary"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type Invoice struct {
	ID              pgtype.UUID        `json:"id"`
	TransactionID   pgtype.UUID        `json:"transactionId"`
	Price           float64            `json:"price"`
	InvoiceImageUrl string             `json:"invoiceImageUrl"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
}

type Transaction struct {
	ID                pgtype.UUID        `json:"id"`
	VehicleOwnerID    pgtype.UUID        `json:"vehicleOwnerId"`
	TransactionType   string             `json:"transactionType"`
	TransactionStatus string             `json:"transactionStatus"`
	RequestDate       pgtype.Timestamptz `json:"requestDate"`
	ResponseDate      pgtype.Timestamptz `json:"responseDate"`
	ESlipImageUrl     pgtype.Text        `json:"eSlipImageUrl"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	Fname       string             `json:"fname"`
	Lname       string             `json:"lname"`
	Password    string             `json:"password"`
	PhoneNumber string             `json:"phoneNumber"`
	Address     string             `json:"address"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type Vehicle struct {
	ID                              pgtype.UUID        `json:"id"`
	RegistrationDate                pgtype.Timestamptz `json:"registrationDate"`
	RegistrationNumber              string             `json:"registrationNumber"`
	Province                        string             `json:"province"`
	VehicleType                     string             `json:"vehicleType"`
	VehicleCategory                 string             `json:"vehicleCategory"`
	Characteristics                 string             `json:"characteristics"`
	Brand                           string             `json:"brand"`
	Model                           string             `json:"model"`
	ModelYear                       string             `json:"modelYear"`
	VehicleColor                    string             `json:"vehicleColor"`
	EngineNumber                    string             `json:"engineNumber"`
	ChasisNumber                    string             `json:"chasisNumber"`
	FuelType                        string             `json:"fuelType"`
	HorsePower                      int32              `json:"horsePower"`
	SeatingCapacity                 int32              `json:"seatingCapacity"`
	WeightUnlanden                  float64            `json:"weightUnlanden"`
	WeightLaden                     float64            `json:"weightLaden"`
	TireCount                       int32              `json:"tireCount"`
	CompulsoryInsurancePolicyNumber string             `json:"compulsoryInsurancePolicyNumber"`
	VoluntaryInsurancePolicyNumber  pgtype.Text        `json:"voluntaryInsurancePolicyNumber"`
	InsuranceType                   pgtype.Text        `json:"insuranceType"`
	CreatedAt                       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt                       pgtype.Timestamptz `json:"updatedAt"`
}

type VehicleOwner struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"userId"`
	VehicleID pgtype.UUID        `json:"vehicleId"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}
