// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package dbmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO "user" (
    email, password, fname, lname, phone_number, address, nationality, birth_date, citizen_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW()
)
`

type CreateUserParams struct {
	Email       string             `json:"email"`
	Password    string             `json:"password"`
	Fname       string             `json:"fname"`
	Lname       string             `json:"lname"`
	PhoneNumber string             `json:"phoneNumber"`
	Address     string             `json:"address"`
	Nationality string             `json:"nationality"`
	BirthDate   pgtype.Timestamptz `json:"birthDate"`
	CitizenID   string             `json:"citizenId"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Email,
		arg.Password,
		arg.Fname,
		arg.Lname,
		arg.PhoneNumber,
		arg.Address,
		arg.Nationality,
		arg.BirthDate,
		arg.CitizenID,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "user"
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, email, fname, lname, password, phone_number, address, nationality, birth_date, citizen_id, created_at, updated_at
FROM "user"
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Fname,
			&i.Lname,
			&i.Password,
			&i.PhoneNumber,
			&i.Address,
			&i.Nationality,
			&i.BirthDate,
			&i.CitizenID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    email,
    fname,
    lname,
    phone_number,
    address,
    nationality,
    birth_date,
    citizen_id
FROM "user"
WHERE id = $1
`

type GetUserByIDRow struct {
	Email       string             `json:"email"`
	Fname       string             `json:"fname"`
	Lname       string             `json:"lname"`
	PhoneNumber string             `json:"phoneNumber"`
	Address     string             `json:"address"`
	Nationality string             `json:"nationality"`
	BirthDate   pgtype.Timestamptz `json:"birthDate"`
	CitizenID   string             `json:"citizenId"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.Email,
		&i.Fname,
		&i.Lname,
		&i.PhoneNumber,
		&i.Address,
		&i.Nationality,
		&i.BirthDate,
		&i.CitizenID,
	)
	return i, err
}

const getUserIDPasswordByEmail = `-- name: GetUserIDPasswordByEmail :one
SELECT
    id,
    password
FROM "user"
WHERE email = $1
`

type GetUserIDPasswordByEmailRow struct {
	ID       pgtype.UUID `json:"id"`
	Password string      `json:"password"`
}

func (q *Queries) GetUserIDPasswordByEmail(ctx context.Context, email string) (GetUserIDPasswordByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserIDPasswordByEmail, email)
	var i GetUserIDPasswordByEmailRow
	err := row.Scan(&i.ID, &i.Password)
	return i, err
}

const getUserIDPasswordByID = `-- name: GetUserIDPasswordByID :one
SELECT
    id,
    password
FROM "user"
WHERE id = $1
`

type GetUserIDPasswordByIDRow struct {
	ID       pgtype.UUID `json:"id"`
	Password string      `json:"password"`
}

func (q *Queries) GetUserIDPasswordByID(ctx context.Context, id pgtype.UUID) (GetUserIDPasswordByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserIDPasswordByID, id)
	var i GetUserIDPasswordByIDRow
	err := row.Scan(&i.ID, &i.Password)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE "user"
SET
    fname = $2,
    lname = $3,
    phone_number = $4,
    address = $5,
    nationality = $6,
    birth_date = $7,
    citizen_id = $8,
    updated_at = NOW()
WHERE id = $1
RETURNING email, fname, lname, phone_number, address, nationality, birth_date, citizen_id
`

type UpdateUserParams struct {
	ID          pgtype.UUID        `json:"id"`
	Fname       string             `json:"fname"`
	Lname       string             `json:"lname"`
	PhoneNumber string             `json:"phoneNumber"`
	Address     string             `json:"address"`
	Nationality string             `json:"nationality"`
	BirthDate   pgtype.Timestamptz `json:"birthDate"`
	CitizenID   string             `json:"citizenId"`
}

type UpdateUserRow struct {
	Email       string             `json:"email"`
	Fname       string             `json:"fname"`
	Lname       string             `json:"lname"`
	PhoneNumber string             `json:"phoneNumber"`
	Address     string             `json:"address"`
	Nationality string             `json:"nationality"`
	BirthDate   pgtype.Timestamptz `json:"birthDate"`
	CitizenID   string             `json:"citizenId"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Fname,
		arg.Lname,
		arg.PhoneNumber,
		arg.Address,
		arg.Nationality,
		arg.BirthDate,
		arg.CitizenID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.Email,
		&i.Fname,
		&i.Lname,
		&i.PhoneNumber,
		&i.Address,
		&i.Nationality,
		&i.BirthDate,
		&i.CitizenID,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE "user"
SET
    password = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID       pgtype.UUID `json:"id"`
	Password string      `json:"password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.Password)
	return err
}
