// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package dbmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (
    email, fname, lname, password, phone_number, address, nationality, birth_date, citizen_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW()
)
RETURNING id, email, fname, lname, phone_number, address, nationality, birth_date, citizen_id
`

type CreateUserParams struct {
	Email       string      `json:"email"`
	Fname       string      `json:"fname"`
	Lname       string      `json:"lname"`
	Password    string      `json:"password"`
	PhoneNumber string      `json:"phoneNumber"`
	Address     string      `json:"address"`
	Nationality string      `json:"nationality"`
	BirthDate   pgtype.Date `json:"birthDate"`
	CitizenID   string      `json:"citizenId"`
}

type CreateUserRow struct {
	ID          pgtype.UUID `json:"id"`
	Email       string      `json:"email"`
	Fname       string      `json:"fname"`
	Lname       string      `json:"lname"`
	PhoneNumber string      `json:"phoneNumber"`
	Address     string      `json:"address"`
	Nationality string      `json:"nationality"`
	BirthDate   pgtype.Date `json:"birthDate"`
	CitizenID   string      `json:"citizenId"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Fname,
		arg.Lname,
		arg.Password,
		arg.PhoneNumber,
		arg.Address,
		arg.Nationality,
		arg.BirthDate,
		arg.CitizenID,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Fname,
		&i.Lname,
		&i.PhoneNumber,
		&i.Address,
		&i.Nationality,
		&i.BirthDate,
		&i.CitizenID,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "user"
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, email, fname, lname, password, phone_number, address, nationality, birth_date, citizen_id, created_at, updated_at
FROM "user"
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Fname,
			&i.Lname,
			&i.Password,
			&i.PhoneNumber,
			&i.Address,
			&i.Nationality,
			&i.BirthDate,
			&i.CitizenID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, fname, lname, password, phone_number, address, nationality, birth_date, citizen_id, created_at, updated_at
FROM "user"
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Fname,
		&i.Lname,
		&i.Password,
		&i.PhoneNumber,
		&i.Address,
		&i.Nationality,
		&i.BirthDate,
		&i.CitizenID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, fname, lname, password, phone_number, address, nationality, birth_date, citizen_id, created_at, updated_at
FROM "user"
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Fname,
		&i.Lname,
		&i.Password,
		&i.PhoneNumber,
		&i.Address,
		&i.Nationality,
		&i.BirthDate,
		&i.CitizenID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE "user"
SET
    email = $2,
    fname = $3,
    lname = $4,
    phone_number = $5,
    address = $6,
    nationality = $7,
    birth_date = $8,
    citizen_id = $9,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, fname, lname, phone_number, address, nationality, birth_date, citizen_id
`

type UpdateUserParams struct {
	ID          pgtype.UUID `json:"id"`
	Email       string      `json:"email"`
	Fname       string      `json:"fname"`
	Lname       string      `json:"lname"`
	PhoneNumber string      `json:"phoneNumber"`
	Address     string      `json:"address"`
	Nationality string      `json:"nationality"`
	BirthDate   pgtype.Date `json:"birthDate"`
	CitizenID   string      `json:"citizenId"`
}

type UpdateUserRow struct {
	ID          pgtype.UUID `json:"id"`
	Email       string      `json:"email"`
	Fname       string      `json:"fname"`
	Lname       string      `json:"lname"`
	PhoneNumber string      `json:"phoneNumber"`
	Address     string      `json:"address"`
	Nationality string      `json:"nationality"`
	BirthDate   pgtype.Date `json:"birthDate"`
	CitizenID   string      `json:"citizenId"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Fname,
		arg.Lname,
		arg.PhoneNumber,
		arg.Address,
		arg.Nationality,
		arg.BirthDate,
		arg.CitizenID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Fname,
		&i.Lname,
		&i.PhoneNumber,
		&i.Address,
		&i.Nationality,
		&i.BirthDate,
		&i.CitizenID,
	)
	return i, err
}
