// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: vehicle_owner.sql

package dbmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVehicleOwner = `-- name: CreateVehicleOwner :one
INSERT INTO "vehicle_owner"(
    user_id,vehicle_id
) VALUES(
    $1, $2
)RETURNING user_id, vehicle_id
`

type CreateVehicleOwnerParams struct {
	UserID    pgtype.UUID `json:"userId"`
	VehicleID pgtype.UUID `json:"vehicleId"`
}

func (q *Queries) CreateVehicleOwner(ctx context.Context, arg CreateVehicleOwnerParams) (VehicleOwner, error) {
	row := q.db.QueryRow(ctx, createVehicleOwner, arg.UserID, arg.VehicleID)
	var i VehicleOwner
	err := row.Scan(&i.UserID, &i.VehicleID)
	return i, err
}

const getAllVehicleOwner = `-- name: GetAllVehicleOwner :many
SELECT
    user_id,
    vehicle_id
from "vehicle_owner"
`

func (q *Queries) GetAllVehicleOwner(ctx context.Context) ([]VehicleOwner, error) {
	rows, err := q.db.Query(ctx, getAllVehicleOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VehicleOwner
	for rows.Next() {
		var i VehicleOwner
		if err := rows.Scan(&i.UserID, &i.VehicleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllVehicleOwnerByUserId = `-- name: GetAllVehicleOwnerByUserId :many
SELECT
    vehicle_id
from "vehicle_owner"
WHERE user_id = $1
`

func (q *Queries) GetAllVehicleOwnerByUserId(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getAllVehicleOwnerByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var vehicle_id pgtype.UUID
		if err := rows.Scan(&vehicle_id); err != nil {
			return nil, err
		}
		items = append(items, vehicle_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
