services:
  api:
    build:
      context: ./docker/
      dockerfile: go-air.Dockerfile
    restart: on-failure
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    networks:
      - sa-se-backend-network
  postgres:
    image: postgres:16-alpine
    restart: on-failure
    volumes:
      - sa-se-web-backend-vol-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Bangkok
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - sa-se-backend-network
volumes:
  sa-se-web-backend-vol-db:
    driver: local
networks:
  sa-se-backend-network:
    driver: bridge
