// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/ThanawatPtd/SAProject/config"
	"github.com/ThanawatPtd/SAProject/domain/usecases"
	"github.com/ThanawatPtd/SAProject/internal/adapters/repositories/psql"
	"github.com/ThanawatPtd/SAProject/internal/adapters/rest"
	"github.com/ThanawatPtd/SAProject/internal/infrastructure/db"
)

import (
	_ "github.com/ThanawatPtd/SAProject/config"
)

// Injectors from wire.go:

func InitializeHandler() *rest.Handler {
	context := ProvideContext()
	configConfig := config.ProvideConfig()
	pool := db.ProvidePgxPool(context, configConfig)
	userRepository := psql.ProvidePostgresUserRepository(pool)
	userUseCase := usecases.ProvideUserService(userRepository)
	userRestHandler := rest.ProvideUserRestHandler(userUseCase)

	employeeRepository := psql.ProvidePostgresEmployeeRepository(pool)
	employeeUseCase := usecases.ProvideEmployeeService(employeeRepository)
	employeeHandler := rest.ProvideEmployeeRestHandler(employeeUseCase)

	handler := rest.ProvideHandler(userRestHandler, employeeHandler)
	return handler
}
